name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.email ${{ secrets.GIT_EMAIL }}
      - run: git config --global user.name "GitHub Actions"
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm version patch
      - run: git push origin main --tags -f
      - uses: actions/upload-artifact@v3
        with:
          name: src
          path: ./
