name: Bump version
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.name != 'GitHubActions' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_USER_TOKEN }}
      - run: git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - run: git config --global user.name 'GitHubActions'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm version patch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_USER_TOKEN }}
          branch: main
          tags: true
      - uses: actions/upload-artifact@v3
        with:
          name: src
          path: ./
